# Generated by Django 4.2.13 on 2024-08-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=50),
        ),
    ]
