# Generated by Django 4.2.13 on 2024-08-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trainers_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainers',
            options={'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
    ]
