version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin12345678
      MYSQL_DATABASE: MySql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /Users/lesia/Documents/python/my_django/workout_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db



volumes:
  db_data:

